meta_product_name: "Arnaud de La Chaise"
meta_title: "Arnaud dLC - Consultant"
meta_description: "Arnaud is a Sydney-based Management and Strategy Consultant with more than 6 years of experience in Oil and Gas, FMCG and Retail in various domains."
meta_image: "arnauddlc_ogimage.png"                       # should exist in `app/assets/images/`
twitter_account: "@tchoupyx"   # required for Twitter Cards